- hosts: dev,prod
  become: yes
  gather_facts: no
  vars:
    webserver: nginx
    webserver_root_dir: /var/www/html
  tasks: 
  - name: debug
    debug:
      msg: "the value of webserver is {{ webserver }}"
  - name: install webserver
    package: 
      name: "{{ webserver }}"
      state: present
    register: nginx_install_output
  - name: print in terminal
    debug:
      var: nginx_install_output
  - name: start webserver
    service:
      name: "{{ webserver }}"
      state: started
  - name: check webserver root directory exists
    file: 
      path: "{{ webserver_root_dir }}"
      state: directory
  - name: deploy static website
    uri:
      url: https://raw.githubusercontent.com/abdennour/example-static-website/{{ git_branch }}/{{ item }}.html
      # root directory of nginx
      dest: "{{ webserver_root_dir }}" # or /usr/share/nginx/html
    # loop variables known as item
    loop:
    - index
    - about


